{{- if .Values.harbor.credentials.password }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "registry.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.harbor.credentialsSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ required "harbor.credentials.username is required when harbor.credentials.password is set" .Values.harbor.credentials.username | quote }}
  password: {{ .Values.harbor.credentials.password | quote }}
{{- end }}
{{- if .Values.harbor.caBundle }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "registry.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "registry.harborCASecretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.harbor.caSecret.key }}: |
    {{- .Values.harbor.caBundle | trim | nindent 4 }}
{{- end }}
