apiVersion: dbaas.opencloud.wso2.com/v1alpha1
kind: DBInstance
metadata:
  labels:
    app.kubernetes.io/name: dbaas
    app.kubernetes.io/managed-by: kustomize
  name: dbinstance-sample
spec:
  dbInstanceClass: db.t3.medium
  allocatedStorage: 50
  engineVersion: "16"
  dbName: myapp
  masterUsername: dbadmin
  # networkRef points at an existing Harvester Multus NAD (namespace/name).
  networkRef: default/vm-net-100
  deletionProtection: true
  running: true
